### ISSUE TITLE
Add a Editorconfig

### ISSUE THREAD

**Issue by c-mueller** [PlanQK/qc-atlas#35]
To prevent merge issues, e.g. due to the use of different spacers (Tabs or Spaces) we should add a editorconfig in order to make sure everything is formatted properly, this will reduce merge conflicts.

**Comment by timniederhausen** [comment]
Right now, people need to manually configure their IDE to use the IntelliJ code style config [here](https://github.com/PlanQK/qc-atlas/blob/7d0bc47488eb2db19052725706081c6bcb07119d/docs/dev/config/IntelliJ%20IDEA/intellij-idea-code-style.xml).
Even if we add an `.editorconfig`, this step wouldn't go away.

We could add a checkstyle pass to our CI config (and fail if there are any issues). This way we don't accidentally merge stuff that violates the style guide.

Another option would be to commit an already configured IntelliJ project and add the per-user config files (for example `workspace.xml`) to `.gitignore`

**Comment by c-mueller** [comment]
The problem is: not everyone seems to be using intellij. The default of intellij in fact are spaces, however eclipse seems to be using spaces instead.

**Comment by timniederhausen** [comment]
Ah, in that case an `.editorconfig` is a good idea.

Not sure how we'd handle other inconsistencies then (for example, different automatic import ordering etc.), but that's something we can handle later.
